{"uid":"c64b327f28b88982","name":"An uncaught error was detected outside of a test","fullName":"cypress/e2e/home.cy.js#An uncaught error was detected outside of a test","historyId":"fd21ab7fd331a8e7625af020db7e19e7:d41d8cd98f00b204e9800998ecf8427e","time":{"start":1722372425511,"stop":1722372425788,"duration":277},"status":"broken","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > Invalid parameters. Use an array or two numbers.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"Error: The following error originated from your test code, not from Cypress.\n\n  > Invalid parameters. Use an array or two numbers.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at getRandomValue (webpack://vox-tecnologia-technical-challenge/./cypress/utils/dataGenerators.js:21:14)\n    at eval (webpack://vox-tecnologia-technical-challenge/./cypress/e2e/home.cy.js:11:31)\n    at eval (https://www.saucedemo.com/__cypress/tests?p=cypress/e2e/home.cy.js:450:3)\n    at eval (https://www.saucedemo.com/__cypress/tests?p=cypress/e2e/home.cy.js:452:12)\n    at eval (<anonymous>)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > Invalid parameters. Use an array or two numbers.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"Error: The following error originated from your test code, not from Cypress.\n\n  > Invalid parameters. Use an array or two numbers.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at getRandomValue (webpack://vox-tecnologia-technical-challenge/./cypress/utils/dataGenerators.js:21:14)\n    at eval (webpack://vox-tecnologia-technical-challenge/./cypress/e2e/home.cy.js:11:31)\n    at eval (https://www.saucedemo.com/__cypress/tests?p=cypress/e2e/home.cy.js:450:3)\n    at eval (https://www.saucedemo.com/__cypress/tests?p=cypress/e2e/home.cy.js:452:12)\n    at eval (<anonymous>)","steps":[],"attachments":[{"uid":"a619feba46cf23c5","name":"Screenshot","source":"a619feba46cf23c5.png","type":"image/png","size":25860}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true},"afterStages":[],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"cypress"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"c64b327f28b88982.json","parameterValues":[]}